version: '3.8'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        env_file:
          - .env
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on: 
            - mysql
    mysql:
        image: mysql:8.0
        container_name: myapp-mysql
        volumes:
          - ./data/mysql:/var/lib/mysql
        environment: 
           - MYSQL_ROOT_PASSWORD=myapp
           - MYSQL_DATABASE=myapp
           - MYSQL_USER=myapp
           - MYSQL_PASSWORD=myapp
        ports:
            - "8001:3306"